apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
  labels:
    app : {{ .Release.Name }}-postgres
spec:
  replicas: {{ .Values.replicaDbCount }}
  selector:
    matchLabels:
      project: postgres
  template:
    metadata:
      labels:
        project: postgres
    spec:
      containers:
        - name : {{ .Values.services.postgres.name }}
          image: postgres:latest
          ports:
            - containerPort: {{ .Values.services.postgres.port }}
          env:
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef: 
                name: app-cm
                key: DB_NAME
          - name: POSTGRES_USER
            valueFrom: 
              secretKeyRef:
                name: secret-data
                key: postgres_username
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: secret-data
                key: postgres_pass
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data  
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.postgres.name }}
  labels:
    env  : prod
    owner: ZhenyaShostak
spec:
  selector:
    project: postgres   
  ports:
    - name      : {{ .Release.Name }}-postgres-listener
      protocol  : TCP
      port: {{ .Values.services.postgres.port }}
      targetPort: {{ .Values.services.postgres.port }}
  type: ClusterIP